/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedRemixRouteImport } from './routes/_authenticated/remix'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as AuthenticatedReviewsIndexRouteImport } from './routes/_authenticated/reviews.index'
import { Route as AuthenticatedReviewsIdRouteImport } from './routes/_authenticated/reviews.$id'
import { Route as AuthenticatedStudioIdRouteImport } from './routes/_authenticated/studio.$id'
import { Route as AuthenticatedStudioNewRouteImport } from './routes/_authenticated/studio.new'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicTiktokThumbRouteImport } from './routes/api/public/tiktok-thumb'
import { Route as TeracRTokenRouteImport } from './routes/terac/r/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemixRoute = AuthenticatedRemixRouteImport.update({
  id: '/remix',
  path: '/remix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewsIndexRoute =
  AuthenticatedReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewsIdRoute = AuthenticatedReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIdRoute = AuthenticatedStudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioNewRoute = AuthenticatedStudioNewRouteImport.update({
  id: '/studio/new',
  path: '/studio/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTiktokThumbRoute = ApiPublicTiktokThumbRouteImport.update({
  id: '/api/public/tiktok-thumb',
  path: '/api/public/tiktok-thumb',
  getParentRoute: () => rootRouteImport,
} as any)
const TeracRTokenRoute = TeracRTokenRouteImport.update({
  id: '/terac/r/$token',
  path: '/terac/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trends': typeof TrendsRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/remix': typeof AuthenticatedRemixRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/studio/$id': typeof AuthenticatedStudioIdRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tiktok-thumb': typeof ApiPublicTiktokThumbRoute
  '/terac/r/$token': typeof TeracRTokenRoute
  '/reviews/': typeof AuthenticatedReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trends': typeof TrendsRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/remix': typeof AuthenticatedRemixRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/studio/$id': typeof AuthenticatedStudioIdRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tiktok-thumb': typeof ApiPublicTiktokThumbRoute
  '/terac/r/$token': typeof TeracRTokenRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/trends': typeof TrendsRoute
  '/_authenticated/ads': typeof AuthenticatedAdsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/remix': typeof AuthenticatedRemixRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/_authenticated/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/_authenticated/studio/$id': typeof AuthenticatedStudioIdRoute
  '/_authenticated/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tiktok-thumb': typeof ApiPublicTiktokThumbRoute
  '/terac/r/$token': typeof TeracRTokenRoute
  '/_authenticated/reviews/': typeof AuthenticatedReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/trends'
    | '/ads'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/knowledge'
    | '/remix'
    | '/categories/$slug'
    | '/companies/$slug'
    | '/reviews/$id'
    | '/studio/$id'
    | '/studio/new'
    | '/api/public/stripe-webhook'
    | '/api/public/tiktok-thumb'
    | '/terac/r/$token'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/trends'
    | '/ads'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/knowledge'
    | '/remix'
    | '/categories/$slug'
    | '/companies/$slug'
    | '/reviews/$id'
    | '/studio/$id'
    | '/studio/new'
    | '/api/public/stripe-webhook'
    | '/api/public/tiktok-thumb'
    | '/terac/r/$token'
    | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/trends'
    | '/_authenticated/ads'
    | '/_authenticated/billing'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge'
    | '/_authenticated/remix'
    | '/categories/$slug'
    | '/companies/$slug'
    | '/_authenticated/reviews/$id'
    | '/_authenticated/studio/$id'
    | '/_authenticated/studio/new'
    | '/api/public/stripe-webhook'
    | '/api/public/tiktok-thumb'
    | '/terac/r/$token'
    | '/_authenticated/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrendsRoute: typeof TrendsRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicTiktokThumbRoute: typeof ApiPublicTiktokThumbRoute
  TeracRTokenRoute: typeof TeracRTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remix': {
      id: '/_authenticated/remix'
      path: '/remix'
      fullPath: '/remix'
      preLoaderRoute: typeof AuthenticatedRemixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reviews/': {
      id: '/_authenticated/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthenticatedReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews/$id': {
      id: '/_authenticated/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof AuthenticatedReviewsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/$id': {
      id: '/_authenticated/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof AuthenticatedStudioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/new': {
      id: '/_authenticated/studio/new'
      path: '/studio/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof AuthenticatedStudioNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok-thumb': {
      id: '/api/public/tiktok-thumb'
      path: '/api/public/tiktok-thumb'
      fullPath: '/api/public/tiktok-thumb'
      preLoaderRoute: typeof ApiPublicTiktokThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terac/r/$token': {
      id: '/terac/r/$token'
      path: '/terac/r/$token'
      fullPath: '/terac/r/$token'
      preLoaderRoute: typeof TeracRTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedRemixRoute: typeof AuthenticatedRemixRoute
  AuthenticatedReviewsIdRoute: typeof AuthenticatedReviewsIdRoute
  AuthenticatedStudioIdRoute: typeof AuthenticatedStudioIdRoute
  AuthenticatedStudioNewRoute: typeof AuthenticatedStudioNewRoute
  AuthenticatedReviewsIndexRoute: typeof AuthenticatedReviewsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdsRoute: AuthenticatedAdsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedRemixRoute: AuthenticatedRemixRoute,
  AuthenticatedReviewsIdRoute: AuthenticatedReviewsIdRoute,
  AuthenticatedStudioIdRoute: AuthenticatedStudioIdRoute,
  AuthenticatedStudioNewRoute: AuthenticatedStudioNewRoute,
  AuthenticatedReviewsIndexRoute: AuthenticatedReviewsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TrendsRoute: TrendsRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicTiktokThumbRoute: ApiPublicTiktokThumbRoute,
  TeracRTokenRoute: TeracRTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
