/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedRemixRouteImport } from './routes/_authenticated/remix'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as AuthenticatedStudioIdRouteImport } from './routes/_authenticated/studio.$id'
import { Route as AuthenticatedStudioNewRouteImport } from './routes/_authenticated/studio.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemixRoute = AuthenticatedRemixRouteImport.update({
  id: '/remix',
  path: '/remix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioIdRoute = AuthenticatedStudioIdRouteImport.update({
  id: '/studio/$id',
  path: '/studio/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioNewRoute = AuthenticatedStudioNewRouteImport.update({
  id: '/studio/new',
  path: '/studio/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/remix': typeof AuthenticatedRemixRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/studio/$id': typeof AuthenticatedStudioIdRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/remix': typeof AuthenticatedRemixRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/studio/$id': typeof AuthenticatedStudioIdRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/remix': typeof AuthenticatedRemixRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/_authenticated/studio/$id': typeof AuthenticatedStudioIdRoute
  '/_authenticated/studio/new': typeof AuthenticatedStudioNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/knowledge'
    | '/remix'
    | '/categories/$slug'
    | '/companies/$slug'
    | '/studio/$id'
    | '/studio/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/knowledge'
    | '/remix'
    | '/categories/$slug'
    | '/companies/$slug'
    | '/studio/$id'
    | '/studio/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge'
    | '/_authenticated/remix'
    | '/categories/$slug'
    | '/companies/$slug'
    | '/_authenticated/studio/$id'
    | '/_authenticated/studio/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remix': {
      id: '/_authenticated/remix'
      path: '/remix'
      fullPath: '/remix'
      preLoaderRoute: typeof AuthenticatedRemixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/$id': {
      id: '/_authenticated/studio/$id'
      path: '/studio/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof AuthenticatedStudioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/new': {
      id: '/_authenticated/studio/new'
      path: '/studio/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof AuthenticatedStudioNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedRemixRoute: typeof AuthenticatedRemixRoute
  AuthenticatedStudioIdRoute: typeof AuthenticatedStudioIdRoute
  AuthenticatedStudioNewRoute: typeof AuthenticatedStudioNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedRemixRoute: AuthenticatedRemixRoute,
  AuthenticatedStudioIdRoute: AuthenticatedStudioIdRoute,
  AuthenticatedStudioNewRoute: AuthenticatedStudioNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
